"""内置模型目录清单 —— 随代码分发的种子数据。

来源不是人工编造：2026-08-04 用各供应商已配置的凭证调它们自己的 `GET /v1/models`
拉回原始列表（387 条），按「本项目 runtime 只跑 chat / embedding / rerank」筛掉非文本
模态、老代模型、日期快照与平台内部条目（→ 213 条），再由管理员在后台逐条过目删剩此表。
所以这里的每一个模型标识都来自上游本身，没有一个是猜的。

清单会过时。上游出了新模型就在这里加一行，或直接在 /admin/settings/catalog 页面
手工添加 —— 两条路进的是同一张表，种子只是「新环境开箱有得选」的底货。
"""

# provider_type -> model_type -> 上游模型标识
CATALOG: dict[str, dict[str, tuple[str, ...]]] = {
    "dashscope": {
        "chat": (
            "deepseek-v4-flash",
            "deepseek-v4-pro",
            "glm-4.7",
            "glm-5",
            "glm-5.1",
            "glm-5.2",
            "glm-5.2-fast-preview",
            "kimi-k2.5",
            "kimi-k2.6",
            "kimi-k2.7-code",
            "kimi/kimi-k2.5",
            "kimi/kimi-k2.6",
            "kimi/kimi-k3",
            "MiniMax-M2.5",
            "MiniMax/MiniMax-M2.5",
            "MiniMax/MiniMax-M2.7",
            "MiniMax/MiniMax-M3",
            "qwen3-235b-a22b",
            "qwen3.7-flash",
            "qwen3.7-max",
            "qwen3.7-max-preview",
            "qwen3.7-plus",
            "qwen3-8b",
            "qwen3.8-max",
            "qwen3-coder-480b-a35b-instruct",
            "qwen3-max",
            "qwen3-max-preview",
            "qwen3-omni-flash",
            "qwen3-vl-flash",
            "qwen3-vl-plus",
            "qwen-max",
            "qwen-max-longcontext",
            "qwen-omni-turbo",
            "qwen-plus",
            "qwen-plus-latest",
            "qwen-turbo",
            "siliconflow/deepseek-v3.2",
            "xiaomi/mimo-v2.5-pro",
            "ZHIPU/GLM-5",
            "ZHIPU/GLM-5.1",
            "ZHIPU/GLM-5.2",
        ),
        "embedding": (
            "qwen3.7-text-embedding",
            "text-embedding-v4",
        ),
    },
    "deepseek": {
        "chat": (
            "deepseek-v4-flash",
            "deepseek-v4-pro",
        ),
    },
    "openai": {
        "chat": (
            "claude-fable-5",
            "claude-haiku-4-5",
            "claude-opus-4-1",
            "claude-opus-4-5",
            "claude-opus-4-6",
            "claude-opus-4-7",
            "claude-opus-4-8",
            "claude-opus-5",
            "claude-sonnet-4",
            "claude-sonnet-4-5",
            "claude-sonnet-4-6",
            "claude-sonnet-5",
            "deepseek-v4-flash",
            "deepseek-v4-flash-free",
            "deepseek-v4-pro",
            "gemini-3.1-pro",
            "gemini-3.5-flash",
            "gemini-3.5-flash-lite",
            "gemini-3.6-flash",
            "gemini-3-flash",
            "glm-4.7",
            "glm-5",
            "glm-5.1",
            "glm-5.2",
            "gpt-4o-mini",
            "gpt-5",
            "gpt-5.1",
            "gpt-5.1-codex",
            "gpt-5.1-codex-max",
            "gpt-5.1-codex-mini",
            "gpt-5.2",
            "gpt-5.2-codex",
            "gpt-5.3-codex",
            "gpt-5.3-codex-spark",
            "gpt-5.4",
            "gpt-5.4-mini",
            "gpt-5.4-nano",
            "gpt-5.4-pro",
            "gpt-5.5",
            "gpt-5.5-pro",
            "gpt-5.6-luna",
            "gpt-5.6-sol",
            "gpt-5.6-terra",
            "gpt-5-codex",
            "gpt-5-nano",
            "grok-4.5",
            "kimi-k2.5",
            "kimi-k2.6",
            "Kimi-K2.6",
            "kimi-k2.7-code",
            "kimi-k3",
            "laguna-s-2.1-free",
            "ling-3.0-flash-free",
            "mimo-v2.5-free",
            "minimax-m2.5",
            "minimax-m2.7",
            "minimax-m3",
            "nemotron-3-ultra-free",
            "north-mini-code-free",
            "qwen3.5-plus",
            "qwen3.6-plus",
        ),
    },
    "siliconflow": {
        "chat": (
            "deepseek-ai/DeepSeek-V4-Flash",
            "deepseek-ai/DeepSeek-V4-Pro",
            "meituan-longcat/LongCat-2.0",
            "MiniMaxAI/MiniMax-M2.5",
            "moonshotai/Kimi-K2.7-Code",
            "Pro/MiniMaxAI/MiniMax-M2.5",
            "Pro/moonshotai/Kimi-K2.6",
            "Pro/zai-org/GLM-5.1",
            "Qwen/Qwen3-14B",
            "Qwen/Qwen3-32B",
            "Qwen/Qwen3.5-122B-A10B",
            "Qwen/Qwen3.5-27B",
            "Qwen/Qwen3.5-35B-A3B",
            "Qwen/Qwen3.5-397B-A17B",
            "Qwen/Qwen3.5-4B",
            "Qwen/Qwen3.5-9B",
            "Qwen/Qwen3.6-27B",
            "Qwen/Qwen3.6-35B-A3B",
            "Qwen/Qwen3-8B",
            "Qwen/Qwen3-Coder-30B-A3B-Instruct",
            "Qwen/Qwen3-Omni-30B-A3B-Instruct",
            "Qwen/Qwen3-Omni-30B-A3B-Thinking",
            "Qwen/Qwen3-VL-30B-A3B-Instruct",
            "Qwen/Qwen3-VL-30B-A3B-Thinking",
            "Qwen/Qwen3-VL-32B-Instruct",
            "Qwen/Qwen3-VL-32B-Thinking",
            "Qwen/Qwen3-VL-8B-Instruct",
            "Qwen/Qwen3-VL-8B-Thinking",
            "tencent/Hunyuan-A13B-Instruct",
            "tencent/Hunyuan-MT-7B",
            "zai-org/GLM-4.5-Air",
            "zai-org/GLM-4.5V",
            "zai-org/GLM-5.2",
        ),
        "embedding": (
            "BAAI/bge-large-en-v1.5",
            "BAAI/bge-large-zh-v1.5",
            "BAAI/bge-m3",
            "Pro/BAAI/bge-m3",
            "Qwen/Qwen3-Embedding-0.6B",
            "Qwen/Qwen3-Embedding-4B",
            "Qwen/Qwen3-Embedding-8B",
            "Qwen/Qwen3-VL-Embedding-8B",
        ),
        "rerank": (
            "BAAI/bge-reranker-v2-m3",
            "Pro/BAAI/bge-reranker-v2-m3",
            "Qwen/Qwen3-Reranker-0.6B",
            "Qwen/Qwen3-Reranker-4B",
            "Qwen/Qwen3-Reranker-8B",
            "Qwen/Qwen3-VL-Reranker-8B",
        ),
    },
}
